### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by yuravg**
I hope these minor changes will be useful

### CODE REVIEW

**Comment by yuravg** [comment]
I found that [this part of pull request 
59ab271](https://github.com/kaushalmodi/.emacs.d/pull/35/commits/59ab27196de563db46484324abe9c3f75e7933e2) is not enough to fix 'counsel-rg-base-command',
should add [this](https://github.com/yuravg/.emacs.d/commit/7903927577d31a3e474034d4ce4dac5cb6f91662)

(I did not immediately find it, because I mainly work in Windows)

**Comment by yuravg** [comment]
I'm sorry ))
I did not think that having deleted the 'yuravg:pull_request' branch in my fork I would close this Pull request

**Comment by kaushalmodi** [comment]
No problem. I will eventually visit your PR's. Been too busy.

**Comment by kaushalmodi** [comment]
.. it's been over a year and still I couldn't get to your PR. Sorry about that.

If you'd still like to submit PR(s), can you break them up into related changes?

**Comment by yuravg** [comment]
ok, I will prepare them

**Pull request closed without merging**
